"""esquema inicial

Revision ID: 0001_esquema_inicial
Revises: 
Create Date: 2025-01-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0001_esquema_inicial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('nombre_completo', sa.String(length=150), nullable=False),
        sa.Column('telefono', sa.String(length=20), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('ingreso_mensual_declarado', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)

    op.create_table(
        'households',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('nombre', sa.String(length=150), nullable=False),
        sa.Column('moneda_base', sa.String(length=3), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'household_members',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('household_id', sa.Uuid(), nullable=False),
        sa.Column('es_tesorero_dinamico', sa.Boolean(), nullable=False),
        sa.Column('fecha_ingreso', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'household_id', name='uq_user_household')
    )
    op.create_index(op.f('ix_household_members_household_id'), 'household_members', ['household_id'], unique=False)
    op.create_index(
        'uq_household_tesorero_dinamico',
        'household_members',
        ['household_id'],
        unique=True,
        postgresql_where=sa.text('es_tesorero_dinamico = true')
    )

    estado_aprobacion_enum = sa.Enum('pendiente', 'aprobado', 'rechazado', name='estado_aprobacion_enum')

    op.create_table(
        'expenses',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('household_id', sa.Uuid(), nullable=False),
        sa.Column('pagado_por_id', sa.Uuid(), nullable=False),
        sa.Column('descripcion', sa.String(length=255), nullable=False),
        sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('monto_total_moneda_base', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('moneda', sa.String(length=3), nullable=False),
        sa.Column('fecha_gasto', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
        sa.Column('estado_aprobacion', estado_aprobacion_enum, nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['pagado_por_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_estado_aprobacion'), 'expenses', ['estado_aprobacion'], unique=False)
    op.create_index(op.f('ix_expenses_household_id'), 'expenses', ['household_id'], unique=False)
    op.create_index(op.f('ix_expenses_pagado_por_id'), 'expenses', ['pagado_por_id'], unique=False)

    op.create_table(
        'expense_splits',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('expense_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('monto_asignado', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('porcentaje_aplicado', sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column('aprobado_por_usuario', sa.Boolean(), nullable=False),
        sa.Column('fecha_aprobacion', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('expense_id', 'user_id', name='uq_expense_user_split')
    )
    op.create_index(op.f('ix_expense_splits_expense_id'), 'expense_splits', ['expense_id'], unique=False)
    op.create_index(op.f('ix_expense_splits_user_id'), 'expense_splits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_splits_user_id'), table_name='expense_splits')
    op.drop_index(op.f('ix_expense_splits_expense_id'), table_name='expense_splits')
    op.drop_table('expense_splits')

    op.drop_index(op.f('ix_expenses_pagado_por_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_household_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_estado_aprobacion'), table_name='expenses')
    op.drop_table('expenses')
    sa.Enum(name='estado_aprobacion_enum').drop(op.get_bind(), checkfirst=False)

    op.drop_index('uq_household_tesorero_dinamico', table_name='household_members', postgresql_where=sa.text('es_tesorero_dinamico = true'))
    op.drop_index(op.f('ix_household_members_household_id'), table_name='household_members')
    op.drop_table('household_members')

    op.drop_table('households')

    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
