"""add monto_total_moneda_base

Revision ID: 0002_add_monto_total_moneda_base
Revises: 0001_esquema_inicial
Create Date: 2025-01-02 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0002_add_monto_total_moneda_base'
down_revision: Union[str, None] = '0001_esquema_inicial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'expenses',
        sa.Column('monto_total_moneda_base', sa.Numeric(precision=12, scale=2), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'monto_total_moneda_base')
    # ### end Alembic commands ###
